AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15